server:
  port: ":443"
  host: "gochatter.app"
  certFile: ".secrets/cfcert.pem"
  keyFile: ".secrets/cfkey.pem"

client:
  serverAddr: "wss://gochatter.app"
  certfile: ".secrets/cfclient.pem"

auth:
  alg: "RS256"
  authurl: "https://dev-hjb4npw6t0kq7cve.us.auth0.com/oauth/token"
  aud: "wss://gochatter.app:443"
  iss: "RwXtHvCrgUgMsu55RZGHHAVh4q3EV9Tj"
  secret: ".secrets/secret"
  keyid: ".secrets/keyid"
  privatekey: ".secrets/pk.pem"
  publickey: ".secrets/pk.pem.pub"
