server:
  port: ":443"
  domain_name: "gochatter.app"
  certFile: ".secrets/cert.pem"
  keyFile: ".secrets/key.pem"

oidc:
  auth0:
    alg: "RS256"
    aud: "wss://gochatter.app:443"
    iss: "RwXtHvCrgUgMsu55RZGHHAVh4q3EV9Tj"
    domain: "dev-hjb4npw6t0kq7cve.us.auth0.com"
    secretpath: ".secrets/clientsecret"
